/**
 * Represents the severity level of a specific detection finding.
 */
export type DetectionSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Categorizes the type of threat or anomaly detected in a log entry.
 */
export type DetectionCategory =
  | 'PROMPT_INJECTION'
  | 'INSTRUCTION_OVERRIDE'
  | 'DATA_EXFILTRATION'
  | 'ROLE_CONFUSION'
  | 'SUSPICIOUS_ENCODING'
  | 'PROMPT_LEAK_ATTEMPT'
  | 'TOOL_ABUSE'
  | 'FORMAT_CONTROL'
  | 'OBFUSCATION'
  | 'BENIGN';

/**
 * Represents the final decision made by the Policy Engine after evaluating the risk score.
 */
export type PolicyDecision = 'SAFE' | 'ESCALATE' | 'HUMAN_REVIEW' | 'BLOCK';

/**
 * Represents a single SIEM-style log entry ingested by the system.
 */
export interface LogEntry {
  /** Unique identifier for the log entry */
  id: string;
  /** Timestamp of when the log was generated */
  timestamp: string;
  /** Source system or component that generated the log */
  source: string;
  /** The actual text content or payload of the log entry */
  payload: string;
  /** Additional metadata attached to the log (e.g., user context) */
  metadata?: Record<string, any>;
}

/**
 * Represents a single anomaly or threat identified by the detection engines.
 */
export interface DetectionFinding {
  /** Unique identifier for this specific finding */
  id: string;
  /** Category of the detection */
  category: DetectionCategory;
  /** Severity level assigned to this finding */
  severity: DetectionSeverity;
  /** Description explaining what triggered the detection */
  description: string;
  /** Identifier of the rule or heuristic that triggered this finding */
  ruleId: string;
  /** The specific text fragment that triggered the detection */
  matchedText?: string;
  /** Character offset where the match was found */
  offset?: number;
  /** Detailed reason for the detection */
  reason?: string;
  /** Confidence level of the detection (0.0 to 1.0) */
  confidence: number;
}

/**
 * Represents a single factor contributing to the total risk score.
 */
export interface ScoringFactor {
  /** The name of the scoring factor (e.g., severity, category) */
  factor: string;
  /** Points added or subtracted by this factor */
  points: number;
  /** Reason for this factor's contribution */
  reason: string;
  /** List of rule IDs associated with this scoring factor */
  relatedRuleIds?: string[];
  /** List of finding IDs associated with this scoring factor */
  relatedFindingIds?: string[];
}

/**
 * Represents the aggregated risk assessment for a given log entry.
 */
export interface RiskScore {
  /** Numeric score representing the overall risk level (e.g., 0-100) */
  score: number;
  /** Confidence level of the score calculation (e.g., 0.0 - 1.0) */
  confidence: number;
  /** Categorical risk level derived from the numeric score */
  level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  /** Breakdown of contributing factors for explainability */
  factors: ScoringFactor[];
}

/**
 * Ground truth metadata from the dataset for evaluation.
 */
export interface GroundTruth {
  label: 'BENIGN' | 'INJECTED';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  attackVector?: string;
  expectedCategory?: string;
  shortDescription?: string;
}

/**
 * Represents the complete end-to-end analysis result for a given log entry.
 */
export interface AnalysisResult {
  /** Unique identifier for the analysis run */
  id: string;
  /** The original log entry that was analyzed */
  inputLog: LogEntry;
  /** List of all detection findings (both deterministic and LLM-assisted) */
  findings: DetectionFinding[];
  /** Final calculated risk score */
  riskScore: RiskScore;
  /** The final deterministic action decided by the Policy Engine */
  policyDecision: PolicyDecision;
  /** Detailed evaluation and overrides from the Policy Engine */
  policyEvaluation: PolicyEvaluation;
  /** Detailed output generated by the Explainability Engine */
  explanation: ExplanationResult;
  /** Time taken in milliseconds to complete the analysis */
  latencyMs: number;
  /** Timestamp of when the analysis was completed */
  createdAt: string;
  /** Ground truth metadata if available (for evaluation) */
  groundTruth?: GroundTruth;
}

/**
 * Represents the result of the preprocessing layer.
 */
export interface NormalizedLogInput {
  /** The original raw input string */
  original: string;
  /** Normalized version (NFKC + decoded) */
  normalized: string;
  /** Lowercase version of the normalized string */
  lowercase: string;
  /** The normalized string split into lines */
  lines: string[];
  /** Different decoded versions if multiple layers of encoding are detected */
  decodedVariants: string[];
  /** List of suspicious transformations detected (e.g., "URL_ENCODING", "HTML_ENTITY", "ZERO_WIDTH_CHARS") */
  suspiciousTransforms: string[];
}

/**
 * Represents the detailed output of the Policy Engine.
 */
export interface PolicyEvaluation {
  /** The final decision made by the policy engine */
  decision: PolicyDecision;
  /** List of reasons for the final decision */
  reasons: string[];
  /** List of specific rule IDs that triggered policy overrides */
  triggeredRules: string[];
  /** The minimum action required based on the most severe finding */
  minimumRequiredAction: PolicyDecision;
  /** Guidance for SOC analysts on how to handle this case */
  analystGuidance: string;
}

/**
 * Represents a specific piece of evidence for a detection finding.
 */
export interface SuspiciousEvidence {
  lineNumber?: number;
  matchedText?: string;
  category: DetectionCategory;
  severity: DetectionSeverity;
  confidence: number;
  reason?: string;
  ruleId?: string;
}

/**
 * Represents the detailed output of the Explainability Engine.
 */
export interface ExplanationResult {
  /** High-level summary of the analysis */
  summary: string;
  /** Detailed rationale for the policy decision */
  decisionRationale: string;
  /** List of concrete evidence found in the log */
  suspiciousEvidence: SuspiciousEvidence[];
  /** Breakdown of how the risk score was calculated */
  scoringBreakdown: ScoringFactor[];
  /** Recommended action for the SOC analyst */
  recommendedAction: string;
  /** Known limitations of this specific analysis */
  limitations: string[];
}

/**
 * Detailed metrics for academic reporting.
 */
export interface EvaluationMetrics {
  totalLogs: number;
  benignCount: number;
  injectedCount: number;
  truePositives: number;
  trueNegatives: number;
  falsePositives: number;
  falseNegatives: number;
  accuracy: number;
  precision: number;
  recall: number;
  f1Score: number;
  detectionRate: number;
  falsePositiveRate: number;
  falseNegativeRate: number;
  averageLatencyMs: number;
}

export interface DifficultyMetric {
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  total: number;
  benignCount: number;
  injectedCount: number;
  truePositives: number;
  trueNegatives: number;
  falsePositives: number;
  falseNegatives: number;
  detectionRateOnInjected: number;
  falsePositiveRateOnBenign: number;
}

export interface AttackVectorMetric {
  attackVector: string;
  total: number;
  detected: number;
  missed: number;
  detectionRate: number;
}

export interface CategoryMetric {
  category: string;
  count: number;
  expectedCount: number;
  coveragePercentage: number;
}

/**
 * Result of the full dataset evaluation benchmark.
 */
export interface DatasetEvaluation {
  metrics: EvaluationMetrics;
  perDifficulty: DifficultyMetric[];
  perAttackVector: AttackVectorMetric[];
  perCategory: CategoryMetric[];
  results: AnalysisResult[];
}
