/**
 * Represents the severity level of a specific detection finding.
 */
export type DetectionSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Categorizes the type of threat or anomaly detected in a log entry.
 */
export type DetectionCategory =
  | 'PROMPT_INJECTION'
  | 'INSTRUCTION_OVERRIDE'
  | 'DATA_EXFILTRATION'
  | 'ROLE_CONFUSION'
  | 'SUSPICIOUS_ENCODING'
  | 'PROMPT_LEAK_ATTEMPT'
  | 'TOOL_ABUSE'
  | 'FORMAT_CONTROL'
  | 'OBFUSCATION'
  | 'BENIGN';

/**
 * Represents the final decision made by the Policy Engine after evaluating the risk score.
 */
export type PolicyDecision = 'SAFE' | 'ESCALATE' | 'HUMAN_REVIEW' | 'BLOCK';

/**
 * Represents a single SIEM-style log entry ingested by the system.
 */
export interface LogEntry {
  /** Unique identifier for the log entry */
  id: string;
  /** Timestamp of when the log was generated */
  timestamp: string;
  /** Source system or component that generated the log */
  source: string;
  /** The actual text content or payload of the log entry */
  payload: string;
  /** Additional metadata attached to the log (e.g., user context) */
  metadata?: Record<string, any>;
}

/**
 * Represents a single anomaly or threat identified by the detection engines.
 */
export interface DetectionFinding {
  /** Unique identifier for this specific finding */
  id: string;
  /** Category of the detection */
  category: DetectionCategory;
  /** Severity level assigned to this finding */
  severity: DetectionSeverity;
  /** Description explaining what triggered the detection */
  description: string;
  /** Identifier of the rule or heuristic that triggered this finding */
  ruleId: string;
  /** The specific text fragment that triggered the detection */
  matchedText?: string;
  /** Character offset where the match was found */
  offset?: number;
  /** Detailed reason for the detection */
  reason?: string;
  /** Confidence level of the detection (0.0 to 1.0) */
  confidence: number;
}

/**
 * Represents a single factor contributing to the total risk score.
 */
export interface ScoringFactor {
  /** The name of the scoring factor (e.g., severity, category) */
  factor: string;
  /** Points added or subtracted by this factor */
  points: number;
  /** Reason for this factor's contribution */
  reason: string;
}

/**
 * Represents the aggregated risk assessment for a given log entry.
 */
export interface RiskScore {
  /** Numeric score representing the overall risk level (e.g., 0-100) */
  score: number;
  /** Confidence level of the score calculation (e.g., 0.0 - 1.0) */
  confidence: number;
  /** Categorical risk level derived from the numeric score */
  level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  /** Breakdown of contributing factors for explainability */
  factors: ScoringFactor[];
}

/**
 * Represents the complete end-to-end analysis result for a given log entry.
 */
export interface AnalysisResult {
  /** Unique identifier for the analysis run */
  id: string;
  /** The original log entry that was analyzed */
  inputLog: LogEntry;
  /** List of all detection findings (both deterministic and LLM-assisted) */
  findings: DetectionFinding[];
  /** Final calculated risk score */
  riskScore: RiskScore;
  /** The final deterministic action decided by the Policy Engine */
  policyDecision: PolicyDecision;
  /** Human-readable rationale generated by the Explainability Engine */
  explanation: string;
  /** Time taken in milliseconds to complete the analysis */
  latencyMs: number;
  /** Timestamp of when the analysis was completed */
  createdAt: string;
}

/**
 * Represents the result of the preprocessing layer.
 */
export interface NormalizedLogInput {
  /** The original raw input string */
  original: string;
  /** Normalized version (NFKC + decoded) */
  normalized: string;
  /** Lowercase version of the normalized string */
  lowercase: string;
  /** The normalized string split into lines */
  lines: string[];
  /** Different decoded versions if multiple layers of encoding are detected */
  decodedVariants: string[];
  /** List of suspicious transformations detected (e.g., "URL_ENCODING", "HTML_ENTITY", "ZERO_WIDTH_CHARS") */
  suspiciousTransforms: string[];
}
